/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Metodos;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Add_Asignatura_Tema extends javax.swing.JFrame {

    /**
     * Creates new form Add_Asignatura_Tema
     */
    public Add_Asignatura_Tema() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            AsigInicio();
        } catch (IOException ex) {
            Logger.getLogger(Add_Asignatura_Tema.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void AsigInicio() throws IOException {
        Metodos e = new Metodos();
        int h = 0;
        try {
            h = e.Generador_de_Combobox("Profesor/Asignatura.txt", ComboAsignatura, h);
            if (h < 1) {
                JOptionPane.showMessageDialog(null, "No hay Asignaturas, deberia agregar alguna.");
            }
        } catch (IOException ex) {
            Logger.getLogger(Añadir_Preguntas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ComboAsignatura = new javax.swing.JComboBox<>();
        ButAsig = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ButtTemas = new javax.swing.JButton();
        AsigText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        check1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        DesA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        DesB = new javax.swing.JTextArea();
        check2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        TemaText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(366, 787));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccion la Asginatura de la cual hace parte el tema");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 320, 28));

        ComboAsignatura.setBackground(new java.awt.Color(255, 153, 102));
        ComboAsignatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        ComboAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAsignaturaActionPerformed(evt);
            }
        });
        jPanel1.add(ComboAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 170, 36));

        ButAsig.setBackground(new java.awt.Color(255, 255, 255));
        ButAsig.setText("Agregar +");
        ButAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAsigActionPerformed(evt);
            }
        });
        jPanel1.add(ButAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Temas");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 310, 30));

        ButtTemas.setText("Agregar +");
        ButtTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtTemasActionPerformed(evt);
            }
        });
        jPanel1.add(ButtTemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 100, 30));
        jPanel1.add(AsigText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 210, 30));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 30));

        check1.setBackground(new java.awt.Color(255, 153, 102));
        check1.setText("Agregar Descripcion");
        check1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check1MouseClicked(evt);
            }
        });
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });
        jPanel1.add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        DesA.setEditable(false);
        DesA.setColumns(20);
        DesA.setRows(5);
        jScrollPane1.setViewportView(DesA);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 310, -1));

        DesB.setEditable(false);
        DesB.setColumns(20);
        DesB.setRows(5);
        jScrollPane2.setViewportView(DesB);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 310, -1));

        check2.setBackground(new java.awt.Color(255, 153, 102));
        check2.setText("Agregar Descripcion");
        check2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check2MouseClicked(evt);
            }
        });
        check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2ActionPerformed(evt);
            }
        });
        jPanel1.add(check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 90, 30));
        jPanel1.add(TemaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 210, 30));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Asignatura");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 310, 28));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 710));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAsignaturaActionPerformed

    }//GEN-LAST:event_ComboAsignaturaActionPerformed

    private void ButAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAsigActionPerformed
        String Asig = AsigText.getText();
        if (!Asig.equals("")) {
            Metodos e = new Metodos();
            String x = "Profesor/Asignatura.txt";
            String temp = null;
            try {
                temp = e.concatenar(x);
                e.guardar(temp, x, Asig + ";" + DesA.getText() + ";");
                ComboAsignatura.addItem(Asig);
                File carpeta = new File("Profesor/" + Asig);
                carpeta.mkdirs();
                File fichero = new File("Profesor/" + Asig + "/Temas.txt");
                fichero.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Añadir_Preguntas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No ha escrito un nombre para la asignatura.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ButAsigActionPerformed

    private void ButtTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtTemasActionPerformed
        String tema = TemaText.getText();
        Metodos e = new Metodos();
        String r = (String) ComboAsignatura.getSelectedItem();
        String x = "Profesor/" + r + "/Temas.txt";
        String temp = null;
        try {
            temp = e.concatenar(x);
            e.guardar(temp, x, tema + ";" + DesB.getText() + ";");
            File carpeta = new File("Profesor/" + r + "/" + tema);
            carpeta.mkdirs();
            File f1 = new File("Profesor/" + r + "/" + tema + "/Preguntas_1.txt");
            f1.createNewFile();
            File f2 = new File("Profesor/" + r + "/" + tema + "/Preguntas_2.txt");
            f2.createNewFile();
            File f3 = new File("Profesor/" + r + "/" + tema + "/Preguntas_3.txt");
            f3.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(Añadir_Preguntas.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtTemasActionPerformed

    private void check1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_check1MouseClicked

    private void check2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_check2MouseClicked

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1ActionPerformed
        if (check1.isSelected() == true) {
            DesA.setEditable(true);
        } else {
            DesA.setEditable(false);
        }
    }//GEN-LAST:event_check1ActionPerformed

    private void check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check2ActionPerformed
        if (check2.isSelected() == true) {
            DesB.setEditable(true);
        } else {
            DesB.setEditable(false);
        }
    }//GEN-LAST:event_check2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Inicio i =new Inicio();
        i.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Asignatura_Tema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Asignatura_Tema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Asignatura_Tema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Asignatura_Tema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Asignatura_Tema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AsigText;
    private javax.swing.JButton ButAsig;
    private javax.swing.JButton ButtTemas;
    private javax.swing.JComboBox<String> ComboAsignatura;
    private javax.swing.JTextArea DesA;
    private javax.swing.JTextArea DesB;
    private javax.swing.JTextField TemaText;
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
